#!/usr/bin/env python
"""
mutt-notmuch-py

This is a Gmail-only version of the original mutt-notmuch script.

It will interactively ask you for a search query and then symlink the matching
messages to $HOME/.cache/mutt_results.

Add this to your muttrc.

macro index / "<enter-command>unset wait_key<enter><shell-escape>mutt-notmuch-py<enter><change-folder-readonly>~/.cache/mutt_results<enter>" \
          "search mail (using notmuch)"

This script overrides the $HOME/.cache/mutt_results each time you run a query.

Install this by adding this file somewhere on your PATH.

Only tested on OSX Lion.

(c) 2012 - Honza Pokorny
Licensed under BSD
"""
import hashlib, sys
from commands import getoutput
from mailbox import Maildir
from optparse import OptionParser


def digest(filename):
    with open(filename) as f:
        return hashlib.sha1(f.read()).hexdigest()


def pick_all_mail(messages):
    for m in messages:
        if 'All Mail' in m:
            return m


def empty_dir(directory):
    box = Maildir(directory)
    box.clear()


def command(cmd):
    return getoutput(cmd)


def main(dest_box):
    query = raw_input('Query: ')

    command('mkdir -p %s' % dest_box)
    command('mkdir -p %s/cur' % dest_box)
    command('mkdir -p %s/new' % dest_box)

    empty_dir(dest_box)
    files = command('notmuch search --output=files "%s"' % query).split('\n')
    for f in files:
        if f:
            command('ln -s "%s" %s/cur/' % (f, dest_box))


if __name__ == '__main__':
    p = OptionParser("usage: %prog [OPTIONS] [RESULTDIR]")
    (options, args) = p.parse_args()

    if args:
        dest = args[0]
    else:
        dest = '~/.cache/mutt_results'

    main(dest.rstrip('/'))
